# fly.toml app configuration file generated for todo-gantt-db on 2024-07-19T19:40:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-gantt-db'
primary_region = 'nrt'

[build]
  image = 'mysql:8'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
app = """--datadir /data/mysql \
  --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "todo-gantt-db"
  MYSQL_USER = "todo-gantt-admin"
